theme = "gruvbox"

 [editor]
 line-number = "relative"
 mouse = true
 bufferline = "always"
 color-modes = true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
# ignore = false

[editor.statusline]
left = ["mode", "spinner", "workspace-diagnostics"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"

[editor.lsp]
display-messages = true 

[keys.normal]
C-y = ":w" 
C-h = ":buffer-previous"
C-l = ":buffer-next"
C-q = ":buffer-close"
C-left = ":buffer-previous"
C-right = ":buffer-next"
C-f = ":format"
